name: Deploy Game Server to Deno Deploy

on:
  push:
    branches: [main]
    paths:
      - 'server/game/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Game Server
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "dhaniverseapi"
          entrypoint: "server/game/index.ts"
          root: "."