name: CI/CD – Deploy Deno WebSocket to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Package server/ws folder
        run: |
          cd server/ws
          zip -r ../../deno-ws.zip . -x "*.git*"

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id:     ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:     ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy the WebSocket server
        uses: azure/webapps-deploy@v3
        with:
          app-name:     "dhaniverse-ws"
          slot-name:    "Production"
          package:      deno-ws.zip
