name: CI/CD – Deploy Deno WebSocket to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Package server folder
        run: |
          cd server
          zip -r ../deno-ws.zip . -x "*.git*"

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false
          audience: api://AzureADTokenExchange
          auth-type: SERVICE_PRINCIPAL

      - name: Deploy the WebSocket server
        uses: azure/webapps-deploy@v3
        with:
          app-name:     "dhaniverse-ws"
          slot-name:    "Production"
          package:      deno-ws.zip
          
      - name: Configure App Settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set --name dhaniverse-ws --resource-group dhaniverse-rg \
              --settings \
              DENO_ENV=production \
              SERVER_DOMAIN=dhaniverse-ws.azurewebsites.net \
              JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              ALLOWED_ORIGINS="https://dhaniverse.vercel.app" \
              AUTH_SERVER_URL="https://dhaniverseapi.deno.dev" \
              PRODUCTION_AUTH_SERVER_URL="https://dhaniverseapi.deno.dev"
