name: CI/CD – Deploy Deno WebSocket to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Package WebSocket server folder
        run: |
          cd server/ws
          zip -r ../../deno-ws.zip . -x "*.git*" -x "*.env"

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy the WebSocket server
        uses: azure/webapps-deploy@v3
        with:
          app-name:     "dhaniverse-ws"
          slot-name:    "Production"
          package:      deno-ws.zip
          
      - name: Configure App Settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set --name dhaniverse-ws --resource-group dhaniverse-rg \
              --settings \
              PORT=8000 \
              DENO_ENV=production \
              JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              ALLOWED_ORIGINS="https://dhaniverse.vercel.app" \
              AUTH_SERVER_URL="https://dhaniverseapi.deno.dev" \
              PRODUCTION_AUTH_SERVER_URL="https://dhaniverseapi.deno.dev"
              
      - name: Configure Deno Runtime
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config set --name dhaniverse-ws --resource-group dhaniverse-rg \
              --startup-file "deno run --allow-net --allow-env --allow-read ws.ts"
